name: digital_sampah
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  get_cli: ^1.8.1
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_launcher_icons: ^0.10.0                                                                                     
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  # image: "assets/logo/logo.png" 
  image_path: "assets/logo/logo.png" 

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/images/backgroundregister.png
    - assets/images/backgroundLupaPassword.png
    - assets/images/ilustrasiSucces.png
    - assets/icons/
    - assets/images/
    - assets/logo/


fonts:
  - family: SF-Pro-Display
    fonts:
      - asset: assets/fonts/SF-Pro-Display-Regular.otf
      - asset: assets/fonts/SF-Pro-Display-Semibold.otf
        weight: 600
      - asset: assets/fonts/SF-Pro-Display-Bold.otf
        weight: 700
